// <auto-generated />
using System;
using Hall_Reservation.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Hall_Reservation.Migrations
{
    [DbContext(typeof(ModelContext))]
    [Migration("20220920091728_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("JOR15_USER88")
                .UseCollation("USING_NLS_COMP")
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.HasSequence("SEQUENCE_DEP_ID");

            modelBuilder.HasSequence("SEQUENCEDEPARTMENT");

            modelBuilder.Entity("Hall_Reservation.Models.AboutU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("BOOKING_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<decimal?>("HomeId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("HOME_ID");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.Property<long?>("PhoneNumber")
                        .HasPrecision(17)
                        .HasColumnType("NUMBER(17)")
                        .HasColumnName("PHONE_NUMBER");

                    b.HasKey("Id")
                        .HasName("ABOUT_US_PK");

                    b.HasIndex("HomeId");

                    b.ToTable("ABOUT_US", "JOR15_USER88");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Address", b =>
                {
                    b.Property<decimal>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ADDRESS_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("AddressId"), 1L, 1);

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("CITY");

                    b.HasKey("AddressId");

                    b.ToTable("ADDRESS", "JOR15_USER88");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Booking", b =>
                {
                    b.Property<decimal>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("BOOKING_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("BookingId"), 1L, 1);

                    b.Property<DateTime>("Creation_Date")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATION_DATE");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("DATE")
                        .HasColumnName("END_DATE");

                    b.Property<decimal?>("HallId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("HALL_ID");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("DATE")
                        .HasColumnName("START_DATE");

                    b.Property<decimal?>("UserId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("USER_ID");

                    b.HasKey("BookingId");

                    b.HasIndex("HallId");

                    b.HasIndex("UserId");

                    b.ToTable("BOOKING", "JOR15_USER88");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Category", b =>
                {
                    b.Property<decimal>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("CAT_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("CatId"), 1L, 1);

                    b.Property<string>("CatImagePath")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("CAT_IMAGE_PATH");

                    b.Property<string>("CatName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("CAT_NAME");

                    b.HasKey("CatId")
                        .HasName("SYS_C00273143");

                    b.ToTable("CATEGORIES", "JOR15_USER88");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Checked", b =>
                {
                    b.Property<decimal>("CheckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("CHECK_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("CheckId"), 1L, 1);

                    b.Property<decimal?>("BookingId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("BOOKING_ID");

                    b.Property<DateTime>("CheckedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("CHECKED_DATE");

                    b.Property<decimal?>("HallId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("HALL_ID");

                    b.Property<decimal?>("Status")
                        .HasColumnType("NUMBER")
                        .HasColumnName("STATUS");

                    b.Property<decimal?>("UserId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("USER_ID");

                    b.HasKey("CheckId")
                        .HasName("SYS_C00273167");

                    b.HasIndex("BookingId");

                    b.HasIndex("HallId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("CHECKED", "JOR15_USER88");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Checklist", b =>
                {
                    b.Property<decimal>("CheckedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("CHECKED_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("CheckedId"), 1L, 1);

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("STATUS");

                    b.HasKey("CheckedId")
                        .HasName("SYS_C00273164");

                    b.ToTable("CHECKLIST", "JOR15_USER88");
                });

            modelBuilder.Entity("Hall_Reservation.Models.ContactU", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<decimal?>("HomeId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("HOME_ID");

                    b.Property<string>("Message")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("MESSAGE");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.Property<long?>("PhoneNumber")
                        .HasPrecision(17)
                        .HasColumnType("NUMBER(17)")
                        .HasColumnName("PHONE_NUMBER");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("CONTACT_US", "JOR15_USER88");
                });

            modelBuilder.Entity("Hall_Reservation.Models.DepView", b =>
                {
                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("LAST_NAME");

                    b.Property<int?>("Salary")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SALARY");

                    b.ToView("DEP_VIEW");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Hall", b =>
                {
                    b.Property<decimal>("HallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("HALL_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("HallId"), 1L, 1);

                    b.Property<decimal?>("AddressId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("ADDRESS_ID");

                    b.Property<decimal>("BookingPrice")
                        .HasColumnType("NUMBER")
                        .HasColumnName("BOOKING_PRICE");

                    b.Property<decimal?>("BuildingNumber")
                        .HasColumnType("NUMBER")
                        .HasColumnName("BUILDING_NUMBER");

                    b.Property<decimal?>("CategoryId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("CATEGORY_ID");

                    b.Property<decimal>("HallCapacity")
                        .HasColumnType("NUMBER")
                        .HasColumnName("HALL_CAPACITY");

                    b.Property<string>("HallDescription")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("HALL_DESCRIPTION");

                    b.Property<string>("HallName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("HALL_NAME");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("IMAGE_PATH");

                    b.Property<string>("Street")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("STREET");

                    b.HasKey("HallId");

                    b.HasIndex("AddressId");

                    b.HasIndex("CategoryId");

                    b.ToTable("HALL", "JOR15_USER88");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Home", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"), 1L, 1);

                    b.Property<string>("Image1")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(250)")
                        .HasColumnName("IMAGE_1");

                    b.Property<string>("Image2")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(250)")
                        .HasColumnName("IMAGE_2");

                    b.Property<string>("Image3")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(250)")
                        .HasColumnName("IMAGE_3");

                    b.Property<string>("Title1")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(250)")
                        .HasColumnName("TITLE_1");

                    b.Property<string>("Title2")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(250)")
                        .HasColumnName("TITLE_2");

                    b.Property<string>("Title3")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(250)")
                        .HasColumnName("TITLE_3");

                    b.HasKey("Id");

                    b.ToTable("HOME", "JOR15_USER88");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Login", b =>
                {
                    b.Property<decimal>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("LOGIN_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("LoginId"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("PASSWORD");

                    b.Property<decimal?>("RolesId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("ROLES_ID");

                    b.Property<decimal?>("UserId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("USER_ID");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("LoginId");

                    b.HasIndex("RolesId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "UserName" }, "SYS_C00273139")
                        .IsUnique();

                    b.ToTable("LOGIN", "JOR15_USER88");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Payment", b =>
                {
                    b.Property<decimal>("PayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("PAY_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("PayId"), 1L, 1);

                    b.Property<decimal?>("BookingId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("BOOKING_ID");

                    b.Property<decimal?>("HallName")
                        .HasColumnType("NUMBER")
                        .HasColumnName("HALL_NAME");

                    b.Property<decimal?>("PayAmount")
                        .HasColumnType("NUMBER")
                        .HasColumnName("PAY_AMOUNT");

                    b.Property<DateTime>("PayDate")
                        .HasColumnType("DATE")
                        .HasColumnName("PAY_DATE");

                    b.Property<string>("PayDesc")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("PAY_DESC");

                    b.Property<decimal?>("PayUserId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("PAY_USER_ID");

                    b.Property<decimal?>("Status")
                        .HasColumnType("NUMBER")
                        .HasColumnName("STATUS");

                    b.Property<decimal?>("VisaId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("VISA_ID");

                    b.HasKey("PayId")
                        .HasName("SYS_C00273174");

                    b.HasIndex("BookingId");

                    b.HasIndex("HallName");

                    b.HasIndex("PayAmount");

                    b.HasIndex("PayUserId");

                    b.HasIndex("Status");

                    b.HasIndex("VisaId");

                    b.ToTable("PAYMENT", "JOR15_USER88");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Review", b =>
                {
                    b.Property<decimal>("ReviewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("REVIEWS_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ReviewsId"), 1L, 1);

                    b.Property<decimal?>("HallId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("HALL_ID");

                    b.Property<string>("Opinion")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("OPINION");

                    b.Property<int?>("Rating")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RATING");

                    b.Property<decimal?>("UserId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("USER_ID");

                    b.HasKey("ReviewsId")
                        .HasName("SYS_C00273154");

                    b.HasIndex("HallId");

                    b.HasIndex("UserId");

                    b.ToTable("REVIEWS", "JOR15_USER88");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Roless", b =>
                {
                    b.Property<decimal>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ROLE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("RoleId"), 1L, 1);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("ROLE_NAME");

                    b.HasKey("RoleId")
                        .HasName("SYS_C00273134");

                    b.ToTable("ROLESS", "JOR15_USER88");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Testimonial", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"), 1L, 1);

                    b.Property<decimal?>("HomeId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("HOME_ID");

                    b.Property<string>("Opinion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("OPINION");

                    b.Property<int?>("Rating")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RATING");

                    b.Property<decimal?>("Status")
                        .HasColumnType("NUMBER")
                        .HasColumnName("STATUS");

                    b.Property<decimal?>("UserId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("TESTIMONIAL", "JOR15_USER88");
                });

            modelBuilder.Entity("Hall_Reservation.Models.User", b =>
                {
                    b.Property<decimal>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("USER_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("UserId"), 1L, 1);

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("FNAME");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("LNAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("PASSWORD");

                    b.Property<long?>("Phonenumber")
                        .HasPrecision(14)
                        .HasColumnType("NUMBER(14)")
                        .HasColumnName("PHONENUMBER");

                    b.Property<string>("UserImage")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("USER_IMAGE");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "UserName" }, "SYS_C00273126")
                        .IsUnique();

                    b.ToTable("USERS", "JOR15_USER88");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Visa", b =>
                {
                    b.Property<decimal>("VisaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("VISA_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("VisaId"), 1L, 1);

                    b.Property<byte?>("CvcCvv")
                        .HasPrecision(3)
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("CVC_CVV");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("DATE")
                        .HasColumnName("END_DATE");

                    b.Property<decimal?>("UserId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("USER_ID");

                    b.Property<decimal>("VisaAmount")
                        .HasColumnType("NUMBER")
                        .HasColumnName("VISA_AMOUNT");

                    b.Property<string>("VisaName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("VISA_NAME");

                    b.Property<long>("VisaNumber")
                        .HasPrecision(16)
                        .HasColumnType("NUMBER(16)")
                        .HasColumnName("VISA_NUMBER");

                    b.HasKey("VisaId");

                    b.HasIndex("UserId");

                    b.ToTable("VISA", "JOR15_USER88");
                });

            modelBuilder.Entity("Hall_Reservation.Models.AboutU", b =>
                {
                    b.HasOne("Hall_Reservation.Models.Home", "Home")
                        .WithMany()
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("SYS_C00273183");

                    b.Navigation("Home");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Booking", b =>
                {
                    b.HasOne("Hall_Reservation.Models.Hall", "Hall")
                        .WithMany("Bookings")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C00273161");

                    b.HasOne("Hall_Reservation.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C00273162");

                    b.Navigation("Hall");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Checked", b =>
                {
                    b.HasOne("Hall_Reservation.Models.Booking", "Booking")
                        .WithMany("Checkeds")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C00273170");

                    b.HasOne("Hall_Reservation.Models.Hall", "Hall")
                        .WithMany("Checkeds")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C00273169");

                    b.HasOne("Hall_Reservation.Models.Checklist", "StatusNavigation")
                        .WithMany("Checkeds")
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C00273171");

                    b.HasOne("Hall_Reservation.Models.User", "User")
                        .WithMany("Checkeds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C00273168");

                    b.Navigation("Booking");

                    b.Navigation("Hall");

                    b.Navigation("StatusNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hall_Reservation.Models.ContactU", b =>
                {
                    b.HasOne("Hall_Reservation.Models.Home", "Home")
                        .WithMany("ContactUs")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("SYS_C00273186");

                    b.Navigation("Home");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Hall", b =>
                {
                    b.HasOne("Hall_Reservation.Models.Address", "Address")
                        .WithMany("Halls")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("SYS_C00273152");

                    b.HasOne("Hall_Reservation.Models.Category", "Category")
                        .WithMany("Halls")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C00273151");

                    b.Navigation("Address");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Login", b =>
                {
                    b.HasOne("Hall_Reservation.Models.Roless", "Roles")
                        .WithMany("Logins")
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C00273141");

                    b.HasOne("Hall_Reservation.Models.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C00273140");

                    b.Navigation("Roles");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Payment", b =>
                {
                    b.HasOne("Hall_Reservation.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C00273180");

                    b.HasOne("Hall_Reservation.Models.Hall", "HallNameNavigation")
                        .WithMany("PaymentHallNameNavigations")
                        .HasForeignKey("HallName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C00273177");

                    b.HasOne("Hall_Reservation.Models.Hall", "PayAmountNavigation")
                        .WithMany("PaymentPayAmountNavigations")
                        .HasForeignKey("PayAmount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C00273176");

                    b.HasOne("Hall_Reservation.Models.User", "PayUser")
                        .WithMany("Payments")
                        .HasForeignKey("PayUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C00273178");

                    b.HasOne("Hall_Reservation.Models.Checked", "StatusNavigation")
                        .WithMany("Payments")
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C00273175");

                    b.HasOne("Hall_Reservation.Models.Visa", "Visa")
                        .WithMany("Payments")
                        .HasForeignKey("VisaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C00273179");

                    b.Navigation("Booking");

                    b.Navigation("HallNameNavigation");

                    b.Navigation("PayAmountNavigation");

                    b.Navigation("PayUser");

                    b.Navigation("StatusNavigation");

                    b.Navigation("Visa");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Review", b =>
                {
                    b.HasOne("Hall_Reservation.Models.Hall", "Hall")
                        .WithMany("Reviews")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C00273156");

                    b.HasOne("Hall_Reservation.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C00273155");

                    b.Navigation("Hall");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Testimonial", b =>
                {
                    b.HasOne("Hall_Reservation.Models.Home", "Home")
                        .WithMany("Testimonials")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("SYS_C00273190");

                    b.HasOne("Hall_Reservation.Models.Checklist", "StatusNavigation")
                        .WithMany("Testimonials")
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C00273191");

                    b.HasOne("Hall_Reservation.Models.User", "User")
                        .WithMany("Testimonials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C00273189");

                    b.Navigation("Home");

                    b.Navigation("StatusNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Visa", b =>
                {
                    b.HasOne("Hall_Reservation.Models.User", "User")
                        .WithMany("Visas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C00273131");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Address", b =>
                {
                    b.Navigation("Halls");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Booking", b =>
                {
                    b.Navigation("Checkeds");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Category", b =>
                {
                    b.Navigation("Halls");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Checked", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Checklist", b =>
                {
                    b.Navigation("Checkeds");

                    b.Navigation("Testimonials");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Hall", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Checkeds");

                    b.Navigation("PaymentHallNameNavigations");

                    b.Navigation("PaymentPayAmountNavigations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Home", b =>
                {
                    b.Navigation("ContactUs");

                    b.Navigation("Testimonials");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Roless", b =>
                {
                    b.Navigation("Logins");
                });

            modelBuilder.Entity("Hall_Reservation.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Checkeds");

                    b.Navigation("Logins");

                    b.Navigation("Payments");

                    b.Navigation("Reviews");

                    b.Navigation("Testimonials");

                    b.Navigation("Visas");
                });

            modelBuilder.Entity("Hall_Reservation.Models.Visa", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
